### ISSUE TITLE
Server Crash on Login

### ISSUE THREAD

**Issue by MadHalaster** [rojo8399/AdventureMMO#2]
When the server is starting up I am receiving the following error:
`Console 02/05/2018 16:29:26
16:29:26 at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_151]
at java.util.stream.LongPipeline.reduce(LongPipeline.java:438) ~[?:1.8.0_151]
at java.util.stream.LongPipeline.sum(LongPipeline.java:396) ~[?:1.8.0_151]
at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526) ~[?:1.8.0_151]
at io.github.nucleuspowered.nucleus.modules.core.datamodules.UniqueUserCountTransientModule.lambda$resetUniqueUserCount$2(UniqueUserCountTransientModule.java:44) ~[UniqueUserCountTransientModule.class:1.2.2-S7.0]
at org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) ~[SchedulerBase.class:1.12.2-2586-7.1.0-BETA-2887]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_151]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_151]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]
Caused by: java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=pool-3-thread-7, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:71) ~[SpongeCauseStackManager.class:1.12.2-2586-7.1.0-BETA-2887]
at org.spongepowered.common.event.SpongeCauseStackManager.getCurrentCause(SpongeCauseStackManager.java:85) ~[SpongeCauseStackManager.class:1.12.2-2586-7.1.0-BETA-2887]
at org.spongepowered.common.data.SpongeKey.getCurrentContainer(SpongeKey.java:79) ~[SpongeKey.class:1.12.2-2586-7.1.0-BETA-2887]
at org.spongepowered.common.data.SpongeKey.<init>(SpongeKey.java:64) ~[SpongeKey.class:1.12.2-2586-7.1.0-BETA-2887]
at org.spongepowered.common.data.SpongeKeyBuilder.build(SpongeKeyBuilder.java:83) ~[SpongeKeyBuilder.class:1.12.2-2586-7.1.0-BETA-2887]
at me.mrdaniel.adventuremmo.data.MMOKeys.<clinit>(MMOKeys.java:22) ~[MMOKeys.class:?]
... 35 more`

Then as soon as I attempt to log into the server it crashes. It was working for hours but is no longer working.

`[16:22:12] [User Authenticator #1/INFO]: UUID of player Halaster is 3ec2e413-2865-4749-9921-97130d158cc7
[16:22:12] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: Could not initialize class me.mrdaniel.adventuremmo.data.MMOKeys
	at me.mrdaniel.adventuremmo.data.manipulators.MMOData.registerGettersAndSetters(MMOData.java:47) ~[MMOData.class:?]
	at me.mrdaniel.adventuremmo.data.manipulators.MMOData.<init>(MMOData.java:42) ~[MMOData.class:?]
	at me.mrdaniel.adventuremmo.data.manipulators.MMOData.<init>(MMOData.java:30) ~[MMOData.class:?]
	at me.mrdaniel.adventuremmo.data.manipulators.MMODataBuilder.create(MMODataBuilder.java:22) ~[MMODataBuilder.class:?]
	at me.mrdaniel.adventuremmo.data.manipulators.MMODataBuilder.buildContent(MMODataBuilder.java:32) ~[MMODataBuilder.class:?]
	at org.spongepowered.api.data.persistence.AbstractDataBuilder.build(AbstractDataBuilder.java:87) ~[AbstractDataBuilder.class:1.12.2-2586-7.1.0-BETA-2887]
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulator$1(DataUtil.java:183) ~[DataUtil.class:1.12.2-2586-7.1.0-BETA-2887]
	at java.util.Optional.flatMap(Optional.java:241) ~[?:1.8.0_151]
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulator(DataUtil.java:183) ~[DataUtil.class:1.12.2-2586-7.1.0-BETA-2887]
	at org.spongepowered.common.data.util.DataUtil.tryDeserializeManipulator(DataUtil.java:169) ~[DataUtil.class:1.12.2-2586-7.1.0-BETA-2887]
	at org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulatorList$0(DataUtil.java:150) ~[DataUtil.class:1.12.2-2586-7.1.0-BETA-2887]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_151]
	at org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:150) ~[DataUtil.class:1.12.2-2586-7.1.0-BETA-2887]
	at org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:208) ~[CustomDataNbtUtil.class:1.12.2-2586-7.1.0-BETA-2887]
	at net.minecraft.entity.Entity.readFromNbt(Entity.java:5786) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.readFromNbt(EntityLivingBase.java:3235) ~[vp.class:?]
	at net.minecraft.entity.player.EntityPlayerMP.readFromNbt(EntityPlayerMP.java:3794) ~[oq.class:?]
	at net.minecraft.entity.Entity.handler$onReadFromNBT$zdp000(Entity.java:5766) ~[vg.class:?]
	at net.minecraft.entity.Entity.func_70020_e(Entity.java:1876) ~[vg.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75752_b(SaveHandler.java:224) ~[bfb.class:?]
	at net.minecraft.server.management.PlayerList.func_72380_a(PlayerList.java:323) ~[pl.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:1461) ~[pl.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:256) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) ~[NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) ~[NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) ~[gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) ~[oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:788) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`

Here is the crash report as well.
[crash-2018-02-05_16.40.14-server.txt](https://github.com/rojo8399/AdventureMMO/files/1697338/crash-2018-02-05_16.40.14-server.txt)

**Comment by MadHalaster** [comment]
I completely wiped out the world to perform a new test and get info on exactly how to reproduce this.

Wipe out the world completely and start server up. 
The following works:
1. Logging in and out of my character repeatedly.
2. Log in and make changes to the world, log out, then restart the server. Log back in when the server is up.
3. Skill increases with AdventureMMO and log in and out without issue.
4. Skill increases with AdventureMMO and make world and item changes, then log in and out without issue. 

What breaks the server:
1. Log into the server, and do an AdventureMMO skill increase, and restart the server.

So it appears that once a skill increase has happened, if the server is restarted it will break. 

[Video of the issue.](https://www.youtube.com/watch?v=gzg1DH0l3ts)

**Comment by MadHalaster** [comment]
I removed all other mods present and tracked this down to having the [Nucleus ](https://nucleuspowered.org/index.html)present. Which is a pretty critical mod.

I have brought this up over at the Nucleus discord as well and supplied logs to see if anyone has any clue, but I think I will probably be directed back here.

**Comment by dualspiral** [comment]
Same problem as https://github.com/trentech/ProjectPortals/issues/86#issuecomment-362788494

**Comment by ronaldburns** [comment]
It's probably because the keys are being registered at the wrong time. Looking into it.

**Comment by MadHalaster** [comment]
Thanks for the quick turnaround again on this.
It no longer appears to crash with the latest build and looks to be good to go.

There is a message when starting the server that appears, but it does not appear to cause any problems from what I can tell.

`/* org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:208) */
/* org.spongepowered.common.entity.player.SpongeUser.readFromNbt(SpongeUser.java:112) */
/* org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:212) */
/* org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:96) */
/* org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:67) */
/* java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) */
/* java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175) */
/* java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553) */
/* java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) */
/* java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) */
/* java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) */
/* java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) */
/* java.util.stream.LongPipeline.reduce(LongPipeline.java:438) */
/* java.util.stream.LongPipeline.sum(LongPipeline.java:396) */
/* java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526) */
/* io.github.nucleuspowered.nucleus.modules.core.datamodules.UniqueUserCountTransientModule.lambda$resetUniqueUserCount$2(UniqueUserCountTransientModule.java:44) */
/* org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186) */
/* java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) */
/* java.util.concurrent.FutureTask.run(FutureTask.java:266) */
/* java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) */
/* java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) */
/* java.lang.Thread.run(Thread.java:748) */
/**********************************************************************************************************************************************************************/`

**Comment by ronaldburns** [comment]
I don't see anything in that with relation to AdventureMMO. Does it happen with only AMMO and also without it?

**Comment by MadHalaster** [comment]
Top part was cut off by my console, sorry about that. Here is the entire output with more usable info at 
 the top.

`/**********************************************************************************************************************************************************************/
/*                                                                       Failed Data Discovery                                                                        */
/**********************************************************************************************************************************************************************/
/* Sponge found an unregistered DataRegistration id. Don't worry though!Sponge will                                                                                   */
/* attempt to persist the failed data for future attempts, unlessthe id is added in                                                                                   */
/* 'data-to-purge' in the sponge/custom-data.cnf                                                                                                                      */
/*                                                                                                                                                                    */
/* Unregistered Id : adventuremmo:mmo-data                                                                                                                            */
/* org.spongepowered.api.data.persistence.InvalidDataException: Could not deserialize adventuremmo:mmo-data!                                                          */
/*     org.spongepowered.common.config.category.CustomDataRegistrationCategory.addFailedData(CustomDataRegistrationCategory.java:107)                                 */
/*     org.spongepowered.common.data.util.DataUtil.addFailedDeserialization(DataUtil.java:187)                                                                        */
/*     org.spongepowered.common.data.util.DataUtil.tryDeserializeManipulator(DataUtil.java:173)                                                                       */
/*     org.spongepowered.common.data.util.DataUtil.lambda$deserializeManipulatorList$0(DataUtil.java:150)                                                             */
/*     java.util.Optional.ifPresent(Optional.java:159)                                                                                                                */
/*     org.spongepowered.common.data.util.DataUtil.deserializeManipulatorList(DataUtil.java:150)                                                                      */
/*     org.spongepowered.common.data.nbt.CustomDataNbtUtil.readCustomData(CustomDataNbtUtil.java:208)                                                                 */
/*     org.spongepowered.common.entity.player.SpongeUser.readFromNbt(SpongeUser.java:112)                                                                             */
/*     org.spongepowered.common.service.user.UserDiscoverer.getFromStoredData(UserDiscoverer.java:212)                                                                */
/*     org.spongepowered.common.service.user.UserDiscoverer.findByProfile(UserDiscoverer.java:96)                                                                     */
/*     org.spongepowered.common.service.user.SpongeUserStorageService.get(SpongeUserStorageService.java:67)                                                           */
/*     java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)                                                                                      */
/*     java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)                                                                                      */
/*     java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1553)                                                                                           */
/*     java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)                                                                                          */
/*     java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)                                                                                   */
/*     java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)                                                                                     */
/*     java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)                                                                                          */
/*     java.util.stream.LongPipeline.reduce(LongPipeline.java:438)                                                                                                    */
/*     java.util.stream.LongPipeline.sum(LongPipeline.java:396)                                                                                                       */
/*     java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526)                                                                                           */
/*     io.github.nucleuspowered.nucleus.modules.core.datamodules.UniqueUserCountTransientModule.lambda$resetUniqueUserCount$2(UniqueUserCountTransientModule.java:44) */
/*     org.spongepowered.common.scheduler.SchedulerBase.lambda$startTask$0(SchedulerBase.java:186)                                                                    */
/*     java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)                                                                                        */
/*     java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                                                       */
/*     java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)                                                                                */
/*     java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)                                                                                */
/*     java.lang.Thread.run(Thread.java:748)                                                                                                                          */
/**********************************************************************************************************************************************************************/`

**Comment by ronaldburns** [comment]
Ahh yeah. Sorry, I removed the plugin-id from the data id as it's not used in API 7, but didn't know that till the last commit.
Hoped it wouldn't be too big of an issue as the plugin's been outdated for a while.
Might need to adapt and accept it.

**Comment by MadHalaster** [comment]
No sorry needed. Just super thankful someone is working on this at all right now. So thanks again for putting your time into sorting through this stuff and getting this all going again.
